version: 0.2
        
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    on-failure: ABORT
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

artifacts:
  files:
    - packaged.yaml
  name: artifact-name
  discard-paths: yes